<?php

/**
 * Implements hook_preprocess_HOOK()
 */
function smart_custom_preprocess_block(&$vars) {
  if($vars['base_plugin_id'] == 'webform_block') {
    $vars['#cache']['max-age'] = 0;
  }
}

/**
 * Implements hook_preprocess_html().
 */
function smart_custom_preprocess_html(&$variables) {
  if ($node = \Drupal::request()->attributes->get('node')) {
    $variables['attributes']['class'][] = 'page-node-' . $node->id();
  }
}

/**
 * Implements hook_page_attachments().
 */
function smart_custom_page_attachments(array &$page) {
  $current_path = \Drupal::service('path.current')->getPath();
  $path_alias = \Drupal::service('path_alias.manager')->getAliasByPath($current_path);
  if ($path_alias == '/thankyou') {
    $javascript_header = "
      gtag('event', 'conversion', {'send_to': 'AW-759610959/aPjECPnglpYBEM_8muoC'});
    ";
    $page['#attached']['html_head'][] = [
      [
        '#tag' => 'script',
        '#value' => \Drupal\Core\Render\Markup::create($javascript_header),
        '#weight' => 0,
      ],
      // A key, to make it possible to recognize this HTML <HEAD> element when altering Testing.
      'key'
    ];
  }
}
