blockgroup.block_group_content.*:
  type: config_entity
  label: 'Block group content config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    uuid:
      type: string
