media_thumbnails_video.settings:
  type: config_object
  label: 'Media thumbnails video settings'
  mapping:
    ffmpeg:
      type: string
      label: 'FFmpeg binary path'
    ffprobe:
      type: string
      label: 'FFprobe binary path'
    timeout:
      type: integer
      label: 'Timeout'
    threads:
      type: integer
      label: 'Threads'
